MVC-Mobile/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Mobile.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int IdStudies { get; set; }
        public Studies Studies { get; set; }
        public string Email { get; set; }
        public int IdTelephone { get; set; }
        public Telephone Telephones { get; set; }
    }
}

MVC-Mobile/Models/Studies.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Mobile.Models
{
    public class Studies
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MVC-Mobile/Models/Telephone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Mobile.Models
{
    public class Telephone
    {
        public int Id { get; set; }
        public int Number { get; set; }
    }
}

MVC-Mobile/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Mobile.Models;

namespace MVC_Mobile.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Contact contacto)
        {
            return View();
        }

    }
}

MVC-Mobile/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace MVC_Mobile.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

MVC-Mobile/Views/Home/Index.cshtml
@model MVC_Mobile.Models.Contact

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using(Html.BeginForm())
{
    
}

MVC-Mobile/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @System.Web.Optimization.Styles.Render("~/Content/jquerymobile/css", "~/Content/Mobile/css")
        @System.Web.Optimization.Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

MVC-Mobile/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}